name = "pais-en-obras"
main = "worker.js"
compatibility_date = "2024-12-18"

[[d1_databases]]
binding = "paisenobras_db"
database_name = "paisenobras-db"
database_id = "97f82682-eb2f-4e4d-908b-948b3aae6a83"
